# Autogenerated by devscripts/update-version.py

__version__ = '2024.07.14.150518'

RELEASE_GIT_HEAD = 'fd61826fc58616df326c036c138551301b935297'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'DunnesH/yt-dlp'

ORIGIN = 'DunnesH/yt-dlp'

_pkg_version = '2024.07.14.150518'
