# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.14.170801'

RELEASE_GIT_HEAD = 'aaac7f42dc226201375ffb8b6218e2d48a075c9e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'DunnesH/yt-dlp'

ORIGIN = 'DunnesH/yt-dlp'

_pkg_version = '2024.04.14.170801'
